version: '3.8'

networks:
    LEMP:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: LEMP-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./www:/www
        depends_on:
            - php
        privileged: true
        networks:
            - LEMP

    php:
        build: ./php
        container_name: LEMP-php
        volumes:
            - ./www:/www
            - ./php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "9000:9000"
        privileged: true
        networks:
            - LEMP

    mysql:
        image: mysql:latest
        container_name: LEMP-mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql/data/:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "project"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        privileged: true
        networks:
            - LEMP

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP-phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 0
            PMA_HOST: "mysql"
            PMA_PORT: 3306
            PMA_USER: "root"
            PMA_PASSWORD: "root"
        depends_on:
            - mysql
        privileged: true
        networks:
            - LEMP
